show_message("Show Message");
show_question("Show Question");
show_message_ext("Show Message Extended One Button", "OK", "", "");
show_message_ext("Show Message Extended Two Buttons", "OK", "Cancel", "");
show_message_ext("Show Message Extended Three Buttons", "Yes", "No", "Cancel");
get_string("Get String", "Default String");
get_integer("Get Integer", 404);
get_open_filename("All Files (*.*)|*.*", "Get Open Filename");
get_open_filename_ext("All Files (*.*)|*.*", "Get Open Filename Extended", "", "Open");
get_open_filenames("All Files (*.*)|*.*", "Get Open Filenames");
get_open_filenames_ext("All Files (*.*)|*.*", "Get Open Filenames Extended", "", "Open");
get_save_filename("All Files (*.*)|*.*", "Get Save Filename");
get_save_filename_ext("All Files (*.*)|*.*", "Get Save Filename Extended", "", "Save As");
get_directory("");
get_directory_alt("Get Directory Alternative", "");
